name: Raspberry Pi 4B Docker Image

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * *

env:
  PREFIX_URL: https://openwrt.cc/releases/targets
  TARGET: bcm27xx
  SUBTARGET: bcm2711
  PLATFORM: aarch64_cortex-a72
  ARCH: linux/arm64
  CLASH_ARCH: armv8
  IMAGE_TAG: rpi4

jobs:
  Publish:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)

    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login To DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Login To Alibaba Cloud Container Registry
      run: |
        docker login -u ${{ secrets.ALIYUN_USERNAME }} -p ${{ secrets.ALIYUN_PWD }} registry.cn-shanghai.aliyuncs.com

    - name: Download Image Builder
      run: |
        wget -q $PREFIX_URL/$TARGET/$SUBTARGET/openwrt-imagebuilder-$TARGET-$SUBTARGET.Linux-x86_64.tar.xz
        wget -q https://raw.githubusercontent.com/coolsnowwolf/lede/master/package/lean/autocore/files/arm/index.htm -O ./files/etc/index.htm

    - name: Load Custom Configuration 
      run: |
        sed -i "s/subtarget/$SUBTARGET/g" files/etc/opkg/distfeeds.conf
        sed -i "s/target\//$TARGET\//g" files/etc/opkg/distfeeds.conf
        sed -i "s/platform/$PLATFORM/g" files/etc/opkg/distfeeds.conf
        chmod +x scripts/*
        ./scripts/preset-clash-core.sh
        ./scripts/preset-terminal-tools.sh
        tar -xJf *.tar.xz
        rm *.tar.xz
        cd openwrt-imagebuilder-$TARGET-$SUBTARGET.Linux-x86_64
        sed -i 's/kmod-/-kmod-/g' include/target.mk
        sed -i 's/luci-app-sfe//g' include/target.mk
        sed -i 's/kmod-/-kmod-/g' target/linux/$TARGET/Makefile
        cp -rf ../files .

    - name: Build RootFS
      run: |
        sed -i 's/autocore/autocore-arm/g' config/packages.config
        sed -i 's/luci-i18n-adbyby-plus-zh-cn //g' config/packages.config
        export packages=$(cat config/packages.config)
        cd openwrt-imagebuilder-$TARGET-$SUBTARGET.Linux-x86_64
        make image PACKAGES="$packages" FILES=files/
        cp bin/targets/$TARGET/$SUBTARGET/*rootfs.tar.gz ..
        cd ..
        rm -rf openwrt-imagebuilder-$TARGET-$SUBTARGET.Linux-x86_64

    - name: Build & Push Multiarch Image
      uses: docker/build-push-action@v2
      with:
        platforms: ${{ env.ARCH }}
        file: Dockerfile
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/openwrt:${{ env.IMAGE_TAG }}
          ${{ secrets.DOCKERHUB_USERNAME }}/openwrt:arm64
          registry.cn-shanghai.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACES }}/openwrt:${{ env.IMAGE_TAG }}
          registry.cn-shanghai.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACES }}/openwrt:arm64
